### ISSUE TITLE
Change state of paused members 

### ISSUE THREAD

**Issue by phollome** [biokiste/backend#10]
- [ ] set state of paused member to ~~3~~ 6
- [ ] migrate paused member data

https://github.com/biokiste/frontend/issues/16#issuecomment-582835041_

**Comment by skoslitz** [comment]
[golang migrate package](https://github.com/golang-migrate/migrate)

**Comment by phollome** [comment]
@skoslitz I've looked again through the data. There is a table `user_states` where `"paused"` is `6`.
