### ISSUE TITLE
Getting user states causes Internal Server Error

### ISSUE THREAD

**Issue by phollome** [biokiste/backend#22]
@skoslitz I wanted to add some more routes we need for the member views. But I've problems with this tasks. First I wanted to add a route for the possible user states but the call always give me the error `sql: no rows in result set`. Please help. 🙏

👉 [route handler on feature branch](https://github.com/biokiste/backend/blob/feature/routes-for-member-views/handlers.go#L451)

**Comment by skoslitz** [comment]
The route `/api/users/{email}` conflicts with route `/api/users/states`.
The handler func `GetUserStates` is not executed, instead `states` is used to look for an email match.
